version: "3.9"

services:
  billboards-frontend:
    image: elonaire/billboards-frontend:latest
    container_name: billboards-frontend # must match the name of the container in the nginx config
    ports:
      - "8080:8080" # this guy needs both ports to be same. -8080:80 will not work
    restart: always
    depends_on:
      - billboards-api
    networks:
      - app-network

  billboards-api:
    image: elonaire/billboards-backend:latest
    container_name: billboards-api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongodb
    volumes:
      - ./uploads:/usr/src/app/uploads
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - billboards-frontend
      - billboards-api
      - mongodb
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  billboards-user:
    image: elonaire/billboards-user:latest
    container_name: billboards-user
    ports:
      - "4200:4200"
      - "4201:4201"
    depends_on:
      - billboards-frontend
      - billboards-api
      - mongodb
    volumes:
      - ./certs:/etc/nginx/certs
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

volumes:
  mongodb-data: {}

networks:
  app-network:
    driver: bridge
